import Foundation

struct Lesson: Identifiable {
    let id = UUID()
    let number: Int
    let title: String
    let words: [ChineseWord]
    
    init(number: Int, title: String, words: [ChineseWord]) {
        self.number = number
        self.title = title
        self.words = words
    }
    
    static let sampleLessons: [Lesson] = [
        Lesson(number: 1, title: "你好 - Xin chào", words: [
            ChineseWord(character: "你好", pinyin: "nǐ hǎo", vietnameseMeaning: "Xin chào", englishMeaning: "Hello",
                       chineseExample: "你好，我是小明", vietnameseExample: "Xin chào, tôi là Tiểu Minh"),
            ChineseWord(character: "早上好", pinyin: "zǎo shang hǎo", vietnameseMeaning: "Chào buổi sáng", englishMeaning: "Good morning",
                       chineseExample: "早上好，今天天气很好", vietnameseExample: "Chào buổi sáng, hôm nay thời tiết đẹp"),
            ChineseWord(character: "晚上好", pinyin: "wǎn shang hǎo", vietnameseMeaning: "Chào buổi tối", englishMeaning: "Good evening",
                       chineseExample: "晚上好，吃饭了吗？", vietnameseExample: "Chào buổi tối, đã ăn cơm chưa?"),
            ChineseWord(character: "再见", pinyin: "zài jiàn", vietnameseMeaning: "Tạm biệt", englishMeaning: "Goodbye",
                       chineseExample: "再见，明天见", vietnameseExample: "Tạm biệt, hẹn gặp ngày mai"),
            ChineseWord(character: "谢谢", pinyin: "xiè xiè", vietnameseMeaning: "Cảm ơn", englishMeaning: "Thank you",
                       chineseExample: "谢谢你的帮助", vietnameseExample: "Cảm ơn sự giúp đỡ của bạn")
        ]),
        Lesson(number: 2, title: "汉语不太难 - Tiếng Hán không khó lắm", words: [
            ChineseWord(character: "一", pinyin: "yī", vietnameseMeaning: "Một", englishMeaning: "One",
                       chineseExample: "一个人", vietnameseExample: "Một người"),
            ChineseWord(character: "二", pinyin: "èr", vietnameseMeaning: "Hai", englishMeaning: "Two",
                       chineseExample: "二十块钱", vietnameseExample: "Hai mươi đồng"),
            ChineseWord(character: "三", pinyin: "sān", vietnameseMeaning: "Ba", englishMeaning: "Three",
                       chineseExample: "三本书", vietnameseExample: "Ba quyển sách"),
            ChineseWord(character: "四", pinyin: "sì", vietnameseMeaning: "Bốn", englishMeaning: "Four",
                       chineseExample: "四点钟", vietnameseExample: "Bốn giờ"),
            ChineseWord(character: "五", pinyin: "wǔ", vietnameseMeaning: "Năm", englishMeaning: "Five",
                       chineseExample: "五个学生", vietnameseExample: "Năm học sinh"),
            ChineseWord(character: "六", pinyin: "liù", vietnameseMeaning: "Sáu", englishMeaning: "Six",
                       chineseExample: "六天", vietnameseExample: "Sáu ngày")
        ]),
        Lesson(number: 3, title: "明天见 - Ngày mai gặp lại", words: [
            ChineseWord(character: "学", pinyin: "xué", vietnameseMeaning: "học", englishMeaning: "to learn; to study",
                       chineseExample: "我学中文", vietnameseExample: "Tôi học tiếng Trung"),
            ChineseWord(character: "英语", pinyin: "Yīngyǔ", vietnameseMeaning: "tiếng Anh", englishMeaning: "English",
                       chineseExample: "我会说英语", vietnameseExample: "Tôi biết nói tiếng Anh"),
            ChineseWord(character: "阿拉伯语", pinyin: "Ālābóyǔ", vietnameseMeaning: "tiếng Ả Rập", englishMeaning: "Arabic",
                       chineseExample: "阿拉伯语很难", vietnameseExample: "Tiếng Ả Rập rất khó"),
            ChineseWord(character: "德语", pinyin: "Déyǔ", vietnameseMeaning: "tiếng Đức", englishMeaning: "German",
                       chineseExample: "我想学德语", vietnameseExample: "Tôi muốn học tiếng Đức"),
            ChineseWord(character: "俄语", pinyin: "Éyǔ", vietnameseMeaning: "tiếng Nga", englishMeaning: "Russian",
                       chineseExample: "你会说俄语吗？", vietnameseExample: "Bạn có biết nói tiếng Nga không?"),
            ChineseWord(character: "法语", pinyin: "Fǎyǔ", vietnameseMeaning: "tiếng Pháp", englishMeaning: "French",
                       chineseExample: "法语很优美", vietnameseExample: "Tiếng Pháp rất đẹp"),
            ChineseWord(character: "韩国语", pinyin: "Hánguóyǔ", vietnameseMeaning: "tiếng Hàn Quốc", englishMeaning: "Korean",
                       chineseExample: "我喜欢韩国语", vietnameseExample: "Tôi thích tiếng Hàn"),
            ChineseWord(character: "日语", pinyin: "Rìyǔ", vietnameseMeaning: "tiếng Nhật", englishMeaning: "Japanese",
                       chineseExample: "日语不难", vietnameseExample: "Tiếng Nhật không khó"),
            ChineseWord(character: "西班牙语", pinyin: "Xībānyáyǔ", vietnameseMeaning: "tiếng Tây Ban Nha", englishMeaning: "Spanish",
                       chineseExample: "西班牙语很流行", vietnameseExample: "Tiếng Tây Ban Nha rất phổ biến")
        ]),
        Lesson(number: 4, title: "你去哪儿 - Bạn đi đâu đấy", words: [
            ChineseWord(character: "今天", pinyin: "jīntiān", vietnameseMeaning: "hôm nay", englishMeaning: "today",
                       chineseExample: "今天天气很好", vietnameseExample: "Hôm nay thời tiết đẹp"),
            ChineseWord(character: "天", pinyin: "tiān", vietnameseMeaning: "ngày", englishMeaning: "day",
                       chineseExample: "今天是个好天", vietnameseExample: "Hôm nay là một ngày đẹp"),
            ChineseWord(character: "昨天", pinyin: "zuótiān", vietnameseMeaning: "hôm qua", englishMeaning: "yesterday",
                       chineseExample: "昨天我去了学校", vietnameseExample: "Hôm qua tôi đã đi học"),
            ChineseWord(character: "对", pinyin: "duì", vietnameseMeaning: "đúng, chính xác", englishMeaning: "right; correct",
                       chineseExample: "你说得对", vietnameseExample: "Bạn nói đúng"),
            ChineseWord(character: "北京", pinyin: "Běijīng", vietnameseMeaning: "Bắc Kinh", englishMeaning: "Beijing",
                       chineseExample: "北京很漂亮", vietnameseExample: "Bắc Kinh rất đẹp"),
            ChineseWord(character: "上海", pinyin: "Shànghǎi", vietnameseMeaning: "Thượng Hải", englishMeaning: "Shanghai",
                       chineseExample: "上海是大城市", vietnameseExample: "Thượng Hải là thành phố lớn"),
            ChineseWord(character: "明天", pinyin: "míngtiān", vietnameseMeaning: "ngày mai", englishMeaning: "tomorrow",
                       chineseExample: "明天见", vietnameseExample: "Hẹn gặp ngày mai"),
            ChineseWord(character: "见", pinyin: "jiàn", vietnameseMeaning: "gặp, thấy", englishMeaning: "to see",
                       chineseExample: "很高兴见到你", vietnameseExample: "Rất vui được gặp bạn"),
            ChineseWord(character: "再见", pinyin: "zàijiàn", vietnameseMeaning: "tạm biệt", englishMeaning: "goodbye",
                       chineseExample: "明天再见", vietnameseExample: "Hẹn gặp lại ngày mai"),
            ChineseWord(character: "去", pinyin: "qù", vietnameseMeaning: "đi, đến", englishMeaning: "to go",
                       chineseExample: "我去学校", vietnameseExample: "Tôi đi học"),
            ChineseWord(character: "邮局", pinyin: "yóujú", vietnameseMeaning: "bưu điện", englishMeaning: "post office",
                       chineseExample: "邮局在哪儿？", vietnameseExample: "Bưu điện ở đâu?"),
            ChineseWord(character: "寄", pinyin: "jì", vietnameseMeaning: "gửi", englishMeaning: "to post; to mail",
                       chineseExample: "我要寄信", vietnameseExample: "Tôi muốn gửi thư"),
            ChineseWord(character: "信", pinyin: "xìn", vietnameseMeaning: "thư", englishMeaning: "letter; mail",
                       chineseExample: "我收到一封信", vietnameseExample: "Tôi nhận được một lá thư"),
            ChineseWord(character: "银行", pinyin: "yínháng", vietnameseMeaning: "ngân hàng", englishMeaning: "bank",
                       chineseExample: "银行在那边", vietnameseExample: "Ngân hàng ở đằng kia"),
            ChineseWord(character: "取", pinyin: "qǔ", vietnameseMeaning: "rút, cử, nhắc", englishMeaning: "to withdraw",
                       chineseExample: "我要取钱", vietnameseExample: "Tôi muốn rút tiền"),
            ChineseWord(character: "钱", pinyin: "qián", vietnameseMeaning: "tiền", englishMeaning: "money",
                       chineseExample: "你有钱吗？", vietnameseExample: "Bạn có tiền không?")
        ]),
        Lesson(number: 5, title: "这是王老师 - Đây là thầy giáo Vương", words: [
            ChineseWord(character: "这", pinyin: "zhè", vietnameseMeaning: "đây, này", englishMeaning: "this", chineseExample: "这是我的书。", vietnameseExample: "Đây là sách của tôi."),
            ChineseWord(character: "是", pinyin: "shì", vietnameseMeaning: "là", englishMeaning: "to be", chineseExample: "他是老师。", vietnameseExample: "Anh ấy là giáo viên."),
            ChineseWord(character: "老师", pinyin: "lǎoshī", vietnameseMeaning: "thầy giáo", englishMeaning: "teacher", chineseExample: "她是我的老师。", vietnameseExample: "Cô ấy là giáo viên của tôi."),
            ChineseWord(character: "您", pinyin: "nín", vietnameseMeaning: "ngài", englishMeaning: "(honorific) you", chineseExample: "您好！", vietnameseExample: "Chào ngài!"),
            ChineseWord(character: "请", pinyin: "qǐng", vietnameseMeaning: "mời", englishMeaning: "please", chineseExample: "请进。", vietnameseExample: "Mời vào."),
            ChineseWord(character: "进", pinyin: "jìn", vietnameseMeaning: "vào", englishMeaning: "to enter", chineseExample: "请进来。", vietnameseExample: "Mời vào trong."),
            ChineseWord(character: "坐", pinyin: "zuò", vietnameseMeaning: "ngồi", englishMeaning: "to sit", chineseExample: "请坐。", vietnameseExample: "Mời ngồi."),
            ChineseWord(character: "喝", pinyin: "hē", vietnameseMeaning: "uống", englishMeaning: "to drink", chineseExample: "请喝茶。", vietnameseExample: "Mời uống trà."),
            ChineseWord(character: "茶", pinyin: "chá", vietnameseMeaning: "trà, chè", englishMeaning: "tea", chineseExample: "我喜欢喝茶。", vietnameseExample: "Tôi thích uống trà."),
            ChineseWord(character: "谢谢", pinyin: "xièxie", vietnameseMeaning: "cảm ơn", englishMeaning: "to thank", chineseExample: "谢谢你。", vietnameseExample: "Cảm ơn bạn."),
            ChineseWord(character: "不客气", pinyin: "bú kèqi", vietnameseMeaning: "không có gì", englishMeaning: "You're welcome", chineseExample: "不客气。", vietnameseExample: "Không có gì."),
            ChineseWord(character: "客气", pinyin: "kèqi", vietnameseMeaning: "khách khí, lịch sự", englishMeaning: "polite; courteous", chineseExample: "他很客气。", vietnameseExample: "Anh ấy rất lịch sự."),
            ChineseWord(character: "工作", pinyin: "gōngzuò", vietnameseMeaning: "công việc, làm việc", englishMeaning: "work; to work", chineseExample: "我在工作。", vietnameseExample: "Tôi đang làm việc."),
            ChineseWord(character: "身体", pinyin: "shēntǐ", vietnameseMeaning: "sức khỏe, thân thể", englishMeaning: "health; body", chineseExample: "身体很好。", vietnameseExample: "Sức khỏe rất tốt."),
            ChineseWord(character: "十", pinyin: "shí", vietnameseMeaning: "mười", englishMeaning: "ten", chineseExample: "我有十本书。", vietnameseExample: "Tôi có mười quyển sách."),
            ChineseWord(character: "日", pinyin: "rì", vietnameseMeaning: "ngày", englishMeaning: "sun; day", chineseExample: "今天是星期日。", vietnameseExample: "Hôm nay là chủ nhật.")
        ]),
        Lesson(number: 6, title: "我学习汉语 - Tôi học tiếng Hán", words: [
            ChineseWord(character: "请问", pinyin: "qǐngwèn", vietnameseMeaning: "xin hỏi", englishMeaning: "Excuse me.", chineseExample: "请问，洗手间在哪里？", vietnameseExample: "Xin hỏi, nhà vệ sinh ở đâu?"),
            ChineseWord(character: "问", pinyin: "wèn", vietnameseMeaning: "hỏi, tìm hiểu", englishMeaning: "to ask; to enquire", chineseExample: "我想问你一个问题。", vietnameseExample: "Tôi muốn hỏi bạn một câu hỏi."),
            ChineseWord(character: "贵姓", pinyin: "guìxìng", vietnameseMeaning: "quý danh", englishMeaning: "May I know your name?", chineseExample: "请问您贵姓？", vietnameseExample: "Xin hỏi quý danh của ngài?"),
            ChineseWord(character: "姓", pinyin: "xìng", vietnameseMeaning: "họ", englishMeaning: "family name", chineseExample: "我姓王。", vietnameseExample: "Tôi họ Vương."),
            ChineseWord(character: "叫", pinyin: "jiào", vietnameseMeaning: "gọi, tên là", englishMeaning: "to call; to name", chineseExample: "我叫张东。", vietnameseExample: "Tôi tên là Trương Đông."),
            ChineseWord(character: "名字", pinyin: "míngzi", vietnameseMeaning: "tên", englishMeaning: "name", chineseExample: "你的名字是什么？", vietnameseExample: "Tên của bạn là gì?"),
            ChineseWord(character: "哪", pinyin: "nǎ", vietnameseMeaning: "nào", englishMeaning: "which; where", chineseExample: "你是哪国人？", vietnameseExample: "Bạn là người nước nào?"),
            ChineseWord(character: "国", pinyin: "guó", vietnameseMeaning: "quốc gia", englishMeaning: "country; nationality", chineseExample: "我来自中国。", vietnameseExample: "Tôi đến từ Trung Quốc."),
            ChineseWord(character: "中国", pinyin: "Zhōngguó", vietnameseMeaning: "Trung Quốc", englishMeaning: "China", chineseExample: "中国很大。", vietnameseExample: "Trung Quốc rất lớn."),
            ChineseWord(character: "德国", pinyin: "Déguó", vietnameseMeaning: "nước Đức", englishMeaning: "Germany", chineseExample: "德国在欧洲。", vietnameseExample: "Nước Đức ở châu Âu."),
            ChineseWord(character: "俄罗斯", pinyin: "Éguó", vietnameseMeaning: "nước Nga", englishMeaning: "Russia", chineseExample: "俄罗斯很冷。", vietnameseExample: "Nước Nga rất lạnh."),
            ChineseWord(character: "法国", pinyin: "Fǎguó", vietnameseMeaning: "nước Pháp", englishMeaning: "France", chineseExample: "法国有埃菲尔铁塔。", vietnameseExample: "Nước Pháp có tháp Eiffel."),
            ChineseWord(character: "韩国", pinyin: "Hánguó", vietnameseMeaning: "Hàn quốc", englishMeaning: "the Republic of Korea", chineseExample: "韩国的首都是首尔。", vietnameseExample: "Thủ đô của Hàn Quốc là Seoul."),
            ChineseWord(character: "美国", pinyin: "Měiguó", vietnameseMeaning: "nước Mỹ", englishMeaning: "the United States", chineseExample: "美国很大。", vietnameseExample: "Nước Mỹ rất lớn."),
            ChineseWord(character: "日本", pinyin: "Rìběn", vietnameseMeaning: "nước Nhật", englishMeaning: "Japan", chineseExample: "日本有富士山。", vietnameseExample: "Nhật Bản có núi Phú Sĩ."),
            ChineseWord(character: "英国", pinyin: "Yīngguó", vietnameseMeaning: "nước Anh", englishMeaning: "Britain", chineseExample: "英国有大本钟。", vietnameseExample: "Nước Anh có đồng hồ Big Ben."),
            ChineseWord(character: "人", pinyin: "rén", vietnameseMeaning: "người", englishMeaning: "human being; man (or woman)", chineseExample: "我是中国人。", vietnameseExample: "Tôi là người Trung Quốc."),
            ChineseWord(character: "学习", pinyin: "xuéxí", vietnameseMeaning: "học tập", englishMeaning: "to study; to learn", chineseExample: "我学习汉语。", vietnameseExample: "Tôi học tiếng Hán."),
            ChineseWord(character: "汉字", pinyin: "Hànzì", vietnameseMeaning: "chữ Hán", englishMeaning: "Chinese characters", chineseExample: "我会写汉字。", vietnameseExample: "Tôi biết viết chữ Hán."),
            ChineseWord(character: "发音", pinyin: "fāyīn", vietnameseMeaning: "phát âm", englishMeaning: "pronunciation; to pronounce", chineseExample: "你的发音很好。", vietnameseExample: "Phát âm của bạn rất tốt."),
            ChineseWord(character: "什么", pinyin: "shénme", vietnameseMeaning: "cái gì", englishMeaning: "what", chineseExample: "你学什么？", vietnameseExample: "Bạn học cái gì?"),
            ChineseWord(character: "书", pinyin: "shū", vietnameseMeaning: "sách", englishMeaning: "book", chineseExample: "我有一本书。", vietnameseExample: "Tôi có một quyển sách."),
            ChineseWord(character: "谁", pinyin: "shéi/shuí", vietnameseMeaning: "ai", englishMeaning: "who", chineseExample: "他是谁？", vietnameseExample: "Anh ấy là ai?"),
            ChineseWord(character: "的", pinyin: "de", vietnameseMeaning: "đích (trợ từ)", englishMeaning: "(a particle used after an attribute to indicate possession)", chineseExample: "这是我的书。", vietnameseExample: "Đây là sách của tôi."),
            ChineseWord(character: "那", pinyin: "nà", vietnameseMeaning: "đó, đấy, kia", englishMeaning: "that", chineseExample: "那是我的朋友。", vietnameseExample: "Đó là bạn của tôi."),
            ChineseWord(character: "杂志", pinyin: "zázhì", vietnameseMeaning: "tạp chí", englishMeaning: "magazine", chineseExample: "我喜欢看杂志。", vietnameseExample: "Tôi thích đọc tạp chí."),
            ChineseWord(character: "…文", pinyin: "…wén", vietnameseMeaning: "ngôn ngữ", englishMeaning: "language", chineseExample: "你会说什么文？", vietnameseExample: "Bạn biết nói ngôn ngữ nào?"),
            ChineseWord(character: "中文", pinyin: "Zhōngwén", vietnameseMeaning: "Trung văn", englishMeaning: "Chinese", chineseExample: "我学习中文。", vietnameseExample: "Tôi học tiếng Trung."),
            ChineseWord(character: "阿拉伯文", pinyin: "Ālābówén", vietnameseMeaning: "tiếng Ả rập", englishMeaning: "Arabic", chineseExample: "他会说阿拉伯文。", vietnameseExample: "Anh ấy biết nói tiếng Ả Rập."),
            ChineseWord(character: "德文", pinyin: "Déwén", vietnameseMeaning: "tiếng Đức", englishMeaning: "German", chineseExample: "我会说德文。", vietnameseExample: "Tôi biết nói tiếng Đức."),
            ChineseWord(character: "俄文", pinyin: "Éwén", vietnameseMeaning: "tiếng Nga", englishMeaning: "Russian", chineseExample: "她会说俄文。", vietnameseExample: "Cô ấy biết nói tiếng Nga."),
            ChineseWord(character: "法文", pinyin: "Fǎwén", vietnameseMeaning: "tiếng Pháp", englishMeaning: "French", chineseExample: "我会说法文。", vietnameseExample: "Tôi biết nói tiếng Pháp."),
            ChineseWord(character: "韩文", pinyin: "Hánwén", vietnameseMeaning: "tiếng Hàn", englishMeaning: "Korean", chineseExample: "他会说韩文。", vietnameseExample: "Anh ấy biết nói tiếng Hàn."),
            ChineseWord(character: "日文", pinyin: "Rìwén", vietnameseMeaning: "tiếng Nhật", englishMeaning: "Japanese", chineseExample: "我会说日文。", vietnameseExample: "Tôi biết nói tiếng Nhật."),
            ChineseWord(character: "西班牙文", pinyin: "Xībānyáwén", vietnameseMeaning: "tiếng Tây Ban Nha", englishMeaning: "Spanish", chineseExample: "我会说西班牙文。", vietnameseExample: "Tôi biết nói tiếng Tây Ban Nha."),
            ChineseWord(character: "英文", pinyin: "Yīngwén", vietnameseMeaning: "tiếng Anh", englishMeaning: "English", chineseExample: "我会说英文。", vietnameseExample: "Tôi biết nói tiếng Anh."),
            ChineseWord(character: "朋友", pinyin: "péngyou", vietnameseMeaning: "bạn bè", englishMeaning: "friend", chineseExample: "他是我的朋友。", vietnameseExample: "Anh ấy là bạn của tôi.")
        ]),
        Lesson(number: 7, title: "你吃什么 - Bạn ăn gì", words: [
            ChineseWord(character: "中午", pinyin: "zhōngwǔ", vietnameseMeaning: "buổi trưa", englishMeaning: "noon", chineseExample: "中午我们去吃饭。", vietnameseExample: "Buổi trưa chúng ta đi ăn cơm."),
            ChineseWord(character: "吃", pinyin: "chī", vietnameseMeaning: "ăn", englishMeaning: "to eat", chineseExample: "我喜欢吃中国菜。", vietnameseExample: "Tôi thích ăn đồ Trung Quốc."),
            ChineseWord(character: "饭", pinyin: "fàn", vietnameseMeaning: "cơm, bữa ăn", englishMeaning: "meal", chineseExample: "我们一起吃饭吧。", vietnameseExample: "Chúng ta cùng ăn cơm nhé."),
            ChineseWord(character: "食堂", pinyin: "shítáng", vietnameseMeaning: "nhà ăn", englishMeaning: "dining hall", chineseExample: "学校食堂的饭很好吃。", vietnameseExample: "Cơm của nhà ăn trường học rất ngon."),
            ChineseWord(character: "馒头", pinyin: "mántou", vietnameseMeaning: "bánh bao chay", englishMeaning: "mantou (steamed bun)", chineseExample: "这个馒头很软。", vietnameseExample: "Cái bánh bao này rất mềm."),
            ChineseWord(character: "米饭", pinyin: "mǐfàn", vietnameseMeaning: "cơm", englishMeaning: "steamed rice", chineseExample: "我每天吃米饭。", vietnameseExample: "Tôi ăn cơm mỗi ngày."),
            ChineseWord(character: "米", pinyin: "mǐ", vietnameseMeaning: "gạo", englishMeaning: "rice", chineseExample: "这个米很香。", vietnameseExample: "Gạo này rất thơm."),
            ChineseWord(character: "要", pinyin: "yào", vietnameseMeaning: "muốn, cần", englishMeaning: "to want; to desire", chineseExample: "我要一碗米饭。", vietnameseExample: "Tôi muốn một bát cơm."),
            ChineseWord(character: "个", pinyin: "gè", vietnameseMeaning: "cái (lượng từ)", englishMeaning: "a classifier basically used before nouns without a special classifier of their own", chineseExample: "一个苹果", vietnameseExample: "Một quả táo"),
            ChineseWord(character: "碗", pinyin: "wǎn", vietnameseMeaning: "bát", englishMeaning: "bowl", chineseExample: "这个碗很大。", vietnameseExample: "Cái bát này rất to."),
            ChineseWord(character: "鸡蛋", pinyin: "jīdàn", vietnameseMeaning: "trứng", englishMeaning: "egg", chineseExample: "我喜欢吃鸡蛋。", vietnameseExample: "Tôi thích ăn trứng."),
            ChineseWord(character: "鸡", pinyin: "jī", vietnameseMeaning: "gà", englishMeaning: "hen; cock; chicken", chineseExample: "那只鸡很肥。", vietnameseExample: "Con gà đó rất béo."),
            ChineseWord(character: "蛋", pinyin: "dàn", vietnameseMeaning: "trứng", englishMeaning: "egg", chineseExample: "这个蛋很新鲜。", vietnameseExample: "Quả trứng này rất tươi."),
            ChineseWord(character: "汤", pinyin: "tāng", vietnameseMeaning: "canh", englishMeaning: "soup", chineseExample: "这个汤很好喝。", vietnameseExample: "Canh này rất ngon."),
            ChineseWord(character: "啤酒", pinyin: "píjiǔ", vietnameseMeaning: "bia", englishMeaning: "beer", chineseExample: "我不喝啤酒。", vietnameseExample: "Tôi không uống bia."),
            ChineseWord(character: "酒", pinyin: "jiǔ", vietnameseMeaning: "rượu", englishMeaning: "alcoholic drink; spirits", chineseExample: "这种酒很贵。", vietnameseExample: "Loại rượu này rất đắt."),
            ChineseWord(character: "这些", pinyin: "zhèxiē", vietnameseMeaning: "những...này", englishMeaning: "these", chineseExample: "这些饺子很好吃。", vietnameseExample: "Những cái bánh chẻo này rất ngon."),
            ChineseWord(character: "些", pinyin: "xiē", vietnameseMeaning: "vài, những", englishMeaning: "some", chineseExample: "一些书", vietnameseExample: "Vài quyển sách"),
            ChineseWord(character: "一些", pinyin: "yìxiē", vietnameseMeaning: "một số", englishMeaning: "some; a few; a little", chineseExample: "我有一些问题。", vietnameseExample: "Tôi có một số câu hỏi."),
            ChineseWord(character: "那些", pinyin: "nàxiē", vietnameseMeaning: "những...kia", englishMeaning: "those", chineseExample: "那些面条很便宜。", vietnameseExample: "Những sợi mì kia rất rẻ."),
            ChineseWord(character: "饺子", pinyin: "jiǎozi", vietnameseMeaning: "há cảo, bánh chẻo", englishMeaning: "jiaozi (dumpling)", chineseExample: "我会包饺子。", vietnameseExample: "Tôi biết gói bánh chẻo."),
            ChineseWord(character: "包子", pinyin: "bāozi", vietnameseMeaning: "bánh bao", englishMeaning: "baozi", chineseExample: "这个包子很香。", vietnameseExample: "Cái bánh bao này rất thơm."),
            ChineseWord(character: "面条", pinyin: "miàntiáor", vietnameseMeaning: "mì sợi", englishMeaning: "noodle", chineseExample: "我爱吃面条。", vietnameseExample: "Tôi rất thích ăn mì sợi."),
            ChineseWord(character: "筷子", pinyin: "kuàizi", vietnameseMeaning: "đũa", englishMeaning: "chopstick", chineseExample: "我用筷子吃饭。", vietnameseExample: "Tôi dùng đũa để ăn cơm."),
            ChineseWord(character: "书", pinyin: "shū", vietnameseMeaning: "sách", englishMeaning: "book", chineseExample: "我喜欢看书。", vietnameseExample: "Tôi thích đọc sách."),
            ChineseWord(character: "词典", pinyin: "cídiǎn", vietnameseMeaning: "từ điển", englishMeaning: "dictionary", chineseExample: "我有一本汉语词典。", vietnameseExample: "Tôi có một quyển từ điển tiếng Hán."),
            ChineseWord(character: "电脑", pinyin: "diànnǎo", vietnameseMeaning: "máy tính", englishMeaning: "computer", chineseExample: "我用电脑学习。", vietnameseExample: "Tôi dùng máy tính để học."),
            ChineseWord(character: "伞", pinyin: "sǎn", vietnameseMeaning: "ô, dù", englishMeaning: "umbrella", chineseExample: "下雨了，我带伞。", vietnameseExample: "Trời mưa rồi, tôi mang ô."),
            ChineseWord(character: "汽车", pinyin: "qìchē", vietnameseMeaning: "xe hơi", englishMeaning: "car", chineseExample: "我有一辆汽车。", vietnameseExample: "Tôi có một chiếc xe hơi."),
            ChineseWord(character: "电视", pinyin: "diànshì", vietnameseMeaning: "tivi", englishMeaning: "TV", chineseExample: "我在看电视。", vietnameseExample: "Tôi đang xem tivi."),
            ChineseWord(character: "录音机", pinyin: "lùyīnjī", vietnameseMeaning: "máy ghi âm", englishMeaning: "recorder", chineseExample: "这是我的录音机。", vietnameseExample: "Đây là máy ghi âm của tôi."),
            ChineseWord(character: "手机", pinyin: "shǒujī", vietnameseMeaning: "điện thoại di động", englishMeaning: "mobile phone", chineseExample: "我有一部手机。", vietnameseExample: "Tôi có một chiếc điện thoại di động.")
        ]),
        Lesson(number: 8, title: "苹果一斤多少钱 - Một cân táo bao nhiêu tiền", words: [
            ChineseWord(character: "买", pinyin: "mǎi", vietnameseMeaning: "mua", englishMeaning: "to buy", chineseExample: "我想买苹果。", vietnameseExample: "Tôi muốn mua táo."),
            ChineseWord(character: "水果", pinyin: "shuǐguǒ", vietnameseMeaning: "hoa quả", englishMeaning: "fruit", chineseExample: "我喜欢吃水果。", vietnameseExample: "Tôi thích ăn hoa quả."),
            ChineseWord(character: "苹果", pinyin: "píngguǒ", vietnameseMeaning: "táo", englishMeaning: "apple", chineseExample: "苹果很好吃。", vietnameseExample: "Táo rất ngon."),
            ChineseWord(character: "斤", pinyin: "jīn", vietnameseMeaning: "cân (0,5kg)", englishMeaning: "a weight unit in China (0.5kg)", chineseExample: "一斤苹果多少钱？", vietnameseExample: "Một cân táo bao nhiêu tiền?"),
            ChineseWord(character: "公斤", pinyin: "gōngjīn", vietnameseMeaning: "cân, kg", englishMeaning: "kilogram", chineseExample: "一公斤香蕉多少钱？", vietnameseExample: "Một cân chuối bao nhiêu tiền?"),
            ChineseWord(character: "贵", pinyin: "guì", vietnameseMeaning: "đắt", englishMeaning: "expensive", chineseExample: "这个苹果很贵。", vietnameseExample: "Quả táo này rất đắt."),
            ChineseWord(character: "了", pinyin: "le", vietnameseMeaning: "trợ từ", englishMeaning: "(modal particle)", chineseExample: "我买了苹果。", vietnameseExample: "Tôi đã mua táo."),
            ChineseWord(character: "吧", pinyin: "ba", vietnameseMeaning: "trợ từ trong câu khẳng định, câu gọi ý, câu yêu cầu", englishMeaning: "a particle used at the end of a sentence, implying soliciting sb.'s advice, suggestion, request or mild command", chineseExample: "我们走吧。", vietnameseExample: "Chúng ta đi nhé."),
            ChineseWord(character: "多少", pinyin: "duōshao", vietnameseMeaning: "bao nhiêu", englishMeaning: "how much, how many", chineseExample: "苹果一斤多少钱？", vietnameseExample: "Một cân táo bao nhiêu tiền?"),
            ChineseWord(character: "多", pinyin: "duō", vietnameseMeaning: "nhiều", englishMeaning: "many; a lot of", chineseExample: "水果很多。", vietnameseExample: "Hoa quả rất nhiều."),
            ChineseWord(character: "少", pinyin: "shǎo", vietnameseMeaning: "ít", englishMeaning: "few; little; less", chineseExample: "苹果很少。", vietnameseExample: "Táo rất ít."),
            ChineseWord(character: "块", pinyin: "kuài", vietnameseMeaning: "đồng (đơn vị tiền)", englishMeaning: "kuai (yuan), a basic money unit in China", chineseExample: "一块钱", vietnameseExample: "Một đồng tiền."),
            ChineseWord(character: "元", pinyin: "yuán", vietnameseMeaning: "nguyên (đơn vị tiền)", englishMeaning: "yuan, a basic money unit in China", chineseExample: "十元", vietnameseExample: "Mười đồng."),
            ChineseWord(character: "角", pinyin: "jiǎo", vietnameseMeaning: "hào", englishMeaning: "jiao (mao), equal to 10% of one kuai", chineseExample: "一角钱", vietnameseExample: "Một hào."),
            ChineseWord(character: "毛", pinyin: "máo", vietnameseMeaning: "hào", englishMeaning: "mao, equal to 10% of one kuai", chineseExample: "五毛钱", vietnameseExample: "Năm hào."),
            ChineseWord(character: "分", pinyin: "fēn", vietnameseMeaning: "xu", englishMeaning: "fen, equal to 1% of one kuai", chineseExample: "一分钱", vietnameseExample: "Một xu."),
            ChineseWord(character: "还", pinyin: "hái", vietnameseMeaning: "còn, vẫn còn", englishMeaning: "also; in addition; still", chineseExample: "我还要买香蕉。", vietnameseExample: "Tôi còn muốn mua chuối."),
            ChineseWord(character: "别的", pinyin: "biéde", vietnameseMeaning: "khác, cái khác", englishMeaning: "other", chineseExample: "你要别的吗？", vietnameseExample: "Bạn muốn cái gì khác không?"),
            ChineseWord(character: "橘子", pinyin: "júzi", vietnameseMeaning: "quýt, quả quýt", englishMeaning: "orange", chineseExample: "我买了橘子。", vietnameseExample: "Tôi đã mua quýt."),
            ChineseWord(character: "怎么", pinyin: "zěnme", vietnameseMeaning: "thế nào", englishMeaning: "how", chineseExample: "怎么卖？", vietnameseExample: "Bán thế nào?"),
            ChineseWord(character: "卖", pinyin: "mài", vietnameseMeaning: "bán", englishMeaning: "to sell", chineseExample: "我卖苹果。", vietnameseExample: "Tôi bán táo."),
            ChineseWord(character: "两", pinyin: "liǎng", vietnameseMeaning: "hai", englishMeaning: "two", chineseExample: "两斤苹果", vietnameseExample: "Hai cân táo."),
            ChineseWord(character: "一共", pinyin: "yígòng", vietnameseMeaning: "tổng cộng", englishMeaning: "altogether", chineseExample: "一共多少钱？", vietnameseExample: "Tổng cộng bao nhiêu tiền?"),
            ChineseWord(character: "给", pinyin: "gěi", vietnameseMeaning: "đưa, cho", englishMeaning: "to give", chineseExample: "我给你钱。", vietnameseExample: "Tôi đưa bạn tiền."),
            ChineseWord(character: "找", pinyin: "zhǎo", vietnameseMeaning: "tìm, trả lại (tiền thừa)", englishMeaning: "to give change", chineseExample: "找你两块钱。", vietnameseExample: "Trả lại bạn hai đồng."),
            ChineseWord(character: "香蕉", pinyin: "xiāngjiāo", vietnameseMeaning: "chuối", englishMeaning: "banana", chineseExample: "我喜欢吃香蕉。", vietnameseExample: "Tôi thích ăn chuối."),
            ChineseWord(character: "葡萄", pinyin: "pútao", vietnameseMeaning: "nho", englishMeaning: "grape", chineseExample: "葡萄很甜。", vietnameseExample: "Nho rất ngọt."),
            ChineseWord(character: "西瓜", pinyin: "xīguā", vietnameseMeaning: "dưa hấu", englishMeaning: "watermelon", chineseExample: "西瓜很大。", vietnameseExample: "Dưa hấu rất to."),
            ChineseWord(character: "梨", pinyin: "lí", vietnameseMeaning: "lê", englishMeaning: "pear", chineseExample: "梨很好吃。", vietnameseExample: "Lê rất ngon."),
            ChineseWord(character: "桃", pinyin: "táo", vietnameseMeaning: "đào", englishMeaning: "peach", chineseExample: "桃很新鲜。", vietnameseExample: "Đào rất tươi."),
            ChineseWord(character: "草莓", pinyin: "cǎoméi", vietnameseMeaning: "dâu tây", englishMeaning: "strawberry", chineseExample: "草莓很红。", vietnameseExample: "Dâu tây rất đỏ.")
        ]),
        Lesson(number: 9, title: "我换人民币 - Tôi đổi tiền nhân dân tệ", words: [
            ChineseWord(character: "下午", pinyin: "xiàwǔ", vietnameseMeaning: "buổi chiều", englishMeaning: "afternoon", chineseExample: "下午好！", vietnameseExample: "Chào buổi chiều!"),
            ChineseWord(character: "上午", pinyin: "shàngwǔ", vietnameseMeaning: "buổi sáng", englishMeaning: "morning", chineseExample: "上午我去图书馆。", vietnameseExample: "Buổi sáng tôi đi thư viện."),
            ChineseWord(character: "图书馆", pinyin: "túshūguǎn", vietnameseMeaning: "thư viện", englishMeaning: "library", chineseExample: "我在图书馆学习。", vietnameseExample: "Tôi học ở thư viện."),
            ChineseWord(character: "要", pinyin: "yào", vietnameseMeaning: "muốn; cần", englishMeaning: "to want to; to wish to", chineseExample: "我要换钱。", vietnameseExample: "Tôi muốn đổi tiền."),
            ChineseWord(character: "换", pinyin: "huàn", vietnameseMeaning: "đổi; thay", englishMeaning: "to change; to exchange", chineseExample: "我换人民币。", vietnameseExample: "Tôi đổi tiền nhân dân tệ."),
            ChineseWord(character: "小姐", pinyin: "xiǎojiě", vietnameseMeaning: "cô gái", englishMeaning: "miss", chineseExample: "小姐，你好。", vietnameseExample: "Chào cô gái."),
            ChineseWord(character: "营业员", pinyin: "yíngyèyuán", vietnameseMeaning: "nhân viên giao dịch, nhân viên cửa hàng", englishMeaning: "shop employees", chineseExample: "营业员很热情。", vietnameseExample: "Nhân viên cửa hàng rất nhiệt tình."),
            ChineseWord(character: "人民币", pinyin: "rénmínbì", vietnameseMeaning: "đồng nhân dân tệ", englishMeaning: "Renminbi; RMB", chineseExample: "我有人民币。", vietnameseExample: "Tôi có đồng nhân dân tệ."),
            ChineseWord(character: "人民", pinyin: "rénmín", vietnameseMeaning: "nhân dân", englishMeaning: "people", chineseExample: "中国人民很友好。", vietnameseExample: "Nhân dân Trung Quốc rất thân thiện."),
            ChineseWord(character: "百", pinyin: "bǎi", vietnameseMeaning: "trăm", englishMeaning: "hundred", chineseExample: "一百元", vietnameseExample: "Một trăm đồng."),
            ChineseWord(character: "千", pinyin: "qiān", vietnameseMeaning: "nghìn", englishMeaning: "thousand", chineseExample: "一千块钱", vietnameseExample: "Một nghìn đồng."),
            ChineseWord(character: "万", pinyin: "wàn", vietnameseMeaning: "mười nghìn, vạn", englishMeaning: "ten thousand", chineseExample: "一万元", vietnameseExample: "Mười nghìn đồng."),
            ChineseWord(character: "美元", pinyin: "měiyuán", vietnameseMeaning: "đô la Mỹ", englishMeaning: "US dollar", chineseExample: "我有美元。", vietnameseExample: "Tôi có đô la Mỹ."),
            ChineseWord(character: "港币", pinyin: "gǎngbì", vietnameseMeaning: "đô la Hồng Kông", englishMeaning: "Hong Kong dollar", chineseExample: "我想换港币。", vietnameseExample: "Tôi muốn đổi đô la Hồng Kông."),
            ChineseWord(character: "日元", pinyin: "rìyuán", vietnameseMeaning: "đồng Yên Nhật", englishMeaning: "Japanese yen", chineseExample: "我有日元。", vietnameseExample: "Tôi có đồng Yên Nhật."),
            ChineseWord(character: "欧元", pinyin: "ōuyuán", vietnameseMeaning: "đồng Euro", englishMeaning: "Euro", chineseExample: "我有欧元。", vietnameseExample: "Tôi có đồng Euro."),
            ChineseWord(character: "等", pinyin: "děng", vietnameseMeaning: "đợi, chờ", englishMeaning: "to wait", chineseExample: "请等一会儿。", vietnameseExample: "Xin đợi một lát."),
            ChineseWord(character: "一会儿", pinyin: "yíhuìr", vietnameseMeaning: "một lúc, một lát", englishMeaning: "a little while", chineseExample: "等一会儿。", vietnameseExample: "Đợi một lát."),
            ChineseWord(character: "先生", pinyin: "xiānsheng", vietnameseMeaning: "ông, ngài", englishMeaning: "Mr.; sir", chineseExample: "王先生，你好。", vietnameseExample: "Chào ông Vương."),
            ChineseWord(character: "数", pinyin: "shǔ", vietnameseMeaning: "đếm", englishMeaning: "to count", chineseExample: "请数一数。", vietnameseExample: "Xin hãy đếm." )
        ]),
        Lesson(number: 10, title: "他住哪儿 - Ông ấy sống ở đâu", words: [
            ChineseWord(character: "办公室", pinyin: "bàngōngshì", vietnameseMeaning: "văn phòng", englishMeaning: "office", chineseExample: "我在办公室工作。", vietnameseExample: "Tôi làm việc ở văn phòng."),
            ChineseWord(character: "办公", pinyin: "bàngōng", vietnameseMeaning: "làm việc (tại cơ quan)", englishMeaning: "to work (in an office)", chineseExample: "他在办公。", vietnameseExample: "Anh ấy đang làm việc."),
            ChineseWord(character: "职员", pinyin: "zhíyuán", vietnameseMeaning: "nhân viên, viên chức", englishMeaning: "employee; office worker", chineseExample: "他是公司职员。", vietnameseExample: "Anh ấy là nhân viên công ty."),
            ChineseWord(character: "找", pinyin: "zhǎo", vietnameseMeaning: "tìm, kiếm", englishMeaning: "to look for", chineseExample: "我找我的朋友。", vietnameseExample: "Tôi tìm bạn của tôi."),
            ChineseWord(character: "在", pinyin: "zài", vietnameseMeaning: "ở, có mặt ở", englishMeaning: "to be in/at; in; at", chineseExample: "我在家。", vietnameseExample: "Tôi ở nhà."),
            ChineseWord(character: "家", pinyin: "jiā", vietnameseMeaning: "nhà", englishMeaning: "home; (a classifier for a family, company, shop, etc.)", chineseExample: "我家在河内。", vietnameseExample: "Nhà tôi ở Hà Nội."),
            ChineseWord(character: "呢", pinyin: "ne", vietnameseMeaning: "trợ từ", englishMeaning: "a modal particle used at the end of a declarative sentence to indicate the continuation of an action or situation", chineseExample: "你呢？", vietnameseExample: "Còn bạn thì sao?"),
            ChineseWord(character: "住", pinyin: "zhù", vietnameseMeaning: "ở, cư trú", englishMeaning: "to live", chineseExample: "我住在北京。", vietnameseExample: "Tôi sống ở Bắc Kinh."),
            ChineseWord(character: "楼", pinyin: "lóu", vietnameseMeaning: "tầng, nhà lầu", englishMeaning: "building", chineseExample: "我家在五楼。", vietnameseExample: "Nhà tôi ở tầng 5."),
            ChineseWord(character: "门", pinyin: "mén", vietnameseMeaning: "cửa, cổng", englishMeaning: "door; gate", chineseExample: "请开门。", vietnameseExample: "Xin mở cửa."),
            ChineseWord(character: "房间", pinyin: "fángjiān", vietnameseMeaning: "phòng", englishMeaning: "room", chineseExample: "我的房间很大。", vietnameseExample: "Phòng của tôi rất lớn."),
            ChineseWord(character: "号", pinyin: "hào", vietnameseMeaning: "số", englishMeaning: "number", chineseExample: "我的房间号是一零一。", vietnameseExample: "Số phòng của tôi là 101."),
            ChineseWord(character: "知道", pinyin: "zhīdào", vietnameseMeaning: "biết", englishMeaning: "to know", chineseExample: "我知道他的名字。", vietnameseExample: "Tôi biết tên của anh ấy."),
            ChineseWord(character: "电话", pinyin: "diànhuà", vietnameseMeaning: "điện thoại", englishMeaning: "telephone", chineseExample: "请打电话给我。", vietnameseExample: "Xin gọi điện cho tôi."),
            ChineseWord(character: "电", pinyin: "diàn", vietnameseMeaning: "điện", englishMeaning: "electricity", chineseExample: "我家有电。", vietnameseExample: "Nhà tôi có điện."),
            ChineseWord(character: "话", pinyin: "huà", vietnameseMeaning: "lời nói", englishMeaning: "words; speech", chineseExample: "他说了很多话。", vietnameseExample: "Anh ấy nói nhiều lời."),
            ChineseWord(character: "号码", pinyin: "hàomǎ", vietnameseMeaning: "số, mã số", englishMeaning: "number", chineseExample: "你的电话号码是多少？", vietnameseExample: "Số điện thoại của bạn là gì?"),
            ChineseWord(character: "零", pinyin: "líng", vietnameseMeaning: "lẻ, số không", englishMeaning: "zero", chineseExample: "我的房间号是零一。", vietnameseExample: "Số phòng của tôi là 01."),
            ChineseWord(character: "手机", pinyin: "shǒujī", vietnameseMeaning: "điện thoại di động", englishMeaning: "mobile phone", chineseExample: "我有一部手机。", vietnameseExample: "Tôi có một chiếc điện thoại di động."),
            ChineseWord(character: "手", pinyin: "shǒu", vietnameseMeaning: "tay", englishMeaning: "hand", chineseExample: "请举手。", vietnameseExample: "Xin giơ tay lên.")
        ]),
        Lesson(number: 11, title: "我们都是留学生 - Chúng tôi đều là lưu học sinh", words: [
            ChineseWord(character: "我们", pinyin: "wǒmen", vietnameseMeaning: "chúng tôi", englishMeaning: "we; us", chineseExample: "我们都是留学生。", vietnameseExample: "Chúng tôi đều là lưu học sinh."),
            ChineseWord(character: "都", pinyin: "dōu", vietnameseMeaning: "đều", englishMeaning: "all; both", chineseExample: "我们都喜欢学中文。", vietnameseExample: "Chúng tôi đều thích học tiếng Trung."),
            ChineseWord(character: "留学生", pinyin: "liúxuéshēng", vietnameseMeaning: "lưu học sinh", englishMeaning: "international student", chineseExample: "我是留学生。", vietnameseExample: "Tôi là lưu học sinh."),
            ChineseWord(character: "留学", pinyin: "liúxué", vietnameseMeaning: "du học", englishMeaning: "to study abroad", chineseExample: "我在中国留学。", vietnameseExample: "Tôi du học ở Trung Quốc."),
            ChineseWord(character: "学生", pinyin: "xuéshēng", vietnameseMeaning: "học sinh", englishMeaning: "student", chineseExample: "我是大学生。", vietnameseExample: "Tôi là sinh viên đại học."),
            ChineseWord(character: "大学", pinyin: "dàxué", vietnameseMeaning: "đại học", englishMeaning: "university", chineseExample: "这是北京大学。", vietnameseExample: "Đây là Đại học Bắc Kinh."),
            ChineseWord(character: "大学生", pinyin: "dàxuéshēng", vietnameseMeaning: "sinh viên đại học", englishMeaning: "university student", chineseExample: "他是大学生。", vietnameseExample: "Anh ấy là sinh viên đại học."),
            ChineseWord(character: "同学", pinyin: "tóngxué", vietnameseMeaning: "bạn học", englishMeaning: "classmate", chineseExample: "她是我的同学。", vietnameseExample: "Cô ấy là bạn học của tôi."),
            ChineseWord(character: "班", pinyin: "bān", vietnameseMeaning: "lớp", englishMeaning: "class", chineseExample: "我们在同一个班。", vietnameseExample: "Chúng tôi học cùng một lớp."),
            ChineseWord(character: "年级", pinyin: "niánjí", vietnameseMeaning: "khóa, cấp lớp", englishMeaning: "grade; year", chineseExample: "我是一年级学生。", vietnameseExample: "Tôi là sinh viên năm nhất."),
            ChineseWord(character: "专业", pinyin: "zhuānyè", vietnameseMeaning: "chuyên ngành", englishMeaning: "major; specialty", chineseExample: "我的专业是汉语。", vietnameseExample: "Chuyên ngành của tôi là tiếng Hán."),
            ChineseWord(character: "学院", pinyin: "xuéyuàn", vietnameseMeaning: "học viện, khoa", englishMeaning: "college; institute", chineseExample: "语言学院很大。", vietnameseExample: "Khoa ngôn ngữ rất lớn."),
            ChineseWord(character: "教室", pinyin: "jiàoshì", vietnameseMeaning: "phòng học", englishMeaning: "classroom", chineseExample: "教室在二楼。", vietnameseExample: "Phòng học ở tầng hai."),
            ChineseWord(character: "课", pinyin: "kè", vietnameseMeaning: "bài học, tiết học", englishMeaning: "lesson; class", chineseExample: "今天有汉语课。", vietnameseExample: "Hôm nay có tiết tiếng Hán."),
            ChineseWord(character: "上课", pinyin: "shàngkè", vietnameseMeaning: "đi học, lên lớp", englishMeaning: "to attend class", chineseExample: "八点上课。", vietnameseExample: "Tám giờ vào học."),
            ChineseWord(character: "下课", pinyin: "xiàkè", vietnameseMeaning: "tan học", englishMeaning: "to finish class", chineseExample: "十点下课。", vietnameseExample: "Mười giờ tan học."),
            ChineseWord(character: "作业", pinyin: "zuòyè", vietnameseMeaning: "bài tập", englishMeaning: "homework", chineseExample: "我做作业。", vietnameseExample: "Tôi làm bài tập."),
            ChineseWord(character: "考试", pinyin: "kǎoshì", vietnameseMeaning: "thi, kiểm tra", englishMeaning: "exam; test", chineseExample: "明天有考试。", vietnameseExample: "Ngày mai có thi."),
            ChineseWord(character: "成绩", pinyin: "chéngjì", vietnameseMeaning: "thành tích, điểm số", englishMeaning: "grade; score", chineseExample: "我的成绩很好。", vietnameseExample: "Điểm số của tôi rất tốt."),
            ChineseWord(character: "教授", pinyin: "jiàoshòu", vietnameseMeaning: "giáo sư", englishMeaning: "professor", chineseExample: "王教授很好。", vietnameseExample: "Giáo sư Vương rất tốt."),
            ChineseWord(character: "认识", pinyin: "rènshi", vietnameseMeaning: "quen biết, nhận biết", englishMeaning: "to know; to recognize", chineseExample: "很高兴认识你。", vietnameseExample: "Rất vui được biết bạn."),
            ChineseWord(character: "介绍", pinyin: "jièshào", vietnameseMeaning: "giới thiệu", englishMeaning: "to introduce", chineseExample: "我介绍一下自己。", vietnameseExample: "Tôi xin tự giới thiệu."),
            ChineseWord(character: "自己", pinyin: "zìjǐ", vietnameseMeaning: "bản thân, mình", englishMeaning: "oneself", chineseExample: "我自己学中文。", vietnameseExample: "Tôi tự học tiếng Trung."),
            ChineseWord(character: "努力", pinyin: "nǔlì", vietnameseMeaning: "cố gắng", englishMeaning: "to make an effort", chineseExample: "我们努力学习。", vietnameseExample: "Chúng tôi cố gắng học tập."),
            ChineseWord(character: "进步", pinyin: "jìnbù", vietnameseMeaning: "tiến bộ", englishMeaning: "progress", chineseExample: "你的中文有进步。", vietnameseExample: "Tiếng Trung của bạn có tiến bộ.")
        ])
    ]
}
